receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # Export traces to Jaeger for visualization
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  
  # Useful for debugging spans in the collector logs
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, logging]
