apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  database-url: "postgres://admin:password@postgres:5432/leave_management"
  jwt-secret: "super-secret-key-change-in-production"
